int32[] leg_number
crab_msgs/LegJointsState[] current_joints

#duration timeout
---
crab_msgs/LegPositionState[] target_position
int32 error_codes

int32 FK_FOUND=1
int32 FK_NOT_FOUND=-1
int32 TIMED_OUT=-2
