set(_CATKIN_CURRENT_PACKAGE "crab_body_kinematics")
set(crab_body_kinematics_VERSION "0.0.0")
set(crab_body_kinematics_MAINTAINER "tuuzdu <tuuzdu@todo.todo>")
set(crab_body_kinematics_PACKAGE_FORMAT "1")
set(crab_body_kinematics_BUILD_DEPENDS "orocos_kdl" "roscpp" "rospy" "std_msgs" "crab_msgs")
set(crab_body_kinematics_BUILD_EXPORT_DEPENDS "orocos_kdl" "roscpp" "rospy" "std_msgs" "crab_msgs")
set(crab_body_kinematics_BUILDTOOL_DEPENDS "catkin")
set(crab_body_kinematics_BUILDTOOL_EXPORT_DEPENDS )
set(crab_body_kinematics_EXEC_DEPENDS "orocos_kdl" "roscpp" "rospy" "std_msgs" "crab_msgs")
set(crab_body_kinematics_RUN_DEPENDS "orocos_kdl" "roscpp" "rospy" "std_msgs" "crab_msgs")
set(crab_body_kinematics_TEST_DEPENDS )
set(crab_body_kinematics_DOC_DEPENDS )
set(crab_body_kinematics_DEPRECATED "")