#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/af/hexapod_ws/src/crab_proj/build-crab_body_kinematics-Desktop_Qt_5_6_0_GCC_64bit-Default/devel:$CMAKE_PREFIX_PATH"
export LD_LIBRARY_PATH="/home/af/hexapod_ws/src/crab_proj/build-crab_body_kinematics-Desktop_Qt_5_6_0_GCC_64bit-Default/devel/lib:/opt/ros/indigo/lib/x86_64-linux-gnu:/home/af/ros_demo/devel_isolated/crab_joint_publisher/lib:/home/af/ros_demo/devel_isolated/crab_body_kinematics/lib:/home/af/ros_demo/devel_isolated/crab_msgs/lib:/home/af/ros_demo/devel_isolated/crab_leg_kinematics/lib:/home/af/ros_demo/devel_isolated/crab_gait/lib:/home/af/ros_demo/devel_isolated/dynamxiel_action_client/lib:/home/af/ros_demo/devel_isolated/dynamixel_tutorials/lib:/home/af/ros_demo/devel_isolated/dynamixel_msgs/lib:/home/af/ros_demo/devel_isolated/dynamixel_driver/lib:/home/af/ros_demo/devel_isolated/dynamixel_controllers/lib:/home/af/ros_demo/devel_isolated/rrbot_gazebo/lib:/home/af/ros_demo/devel_isolated/rrbot_description/lib:/home/af/ros_demo/devel_isolated/rrbot_control/lib:/home/af/ros_demo/devel_isolated/pr2_controller_manager/lib:/home/af/ros_demo/devel_isolated/pr2_mechanism_diagnostics/lib:/home/af/ros_demo/devel_isolated/my_controller_pkg/lib:/home/af/ros_demo/devel_isolated/pr2_controller_interface/lib:/home/af/ros_demo/devel_isolated/pr2_mechanism_model/lib:/home/af/ros_demo/devel_isolated/pr2_hardware_interface/lib:/home/af/ros_demo/devel_isolated/pluginlib_calculator/lib:/home/af/ros_demo/devel_isolated/my_pluginlib_calculator/lib:/home/af/ros_demo/devel_isolated/gazebo_tutorials/lib:/home/af/human_ws/devel/lib:/home/af/moveit/devel/lib:/home/af/hexapod_ws/devel/lib:/home/af/catkin_ws/devel/lib:/opt/ros/indigo/lib"
export PATH="/opt/ros/indigo/bin:/opt/Qt/5.6/gcc_64/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export PKG_CONFIG_PATH="/home/af/hexapod_ws/src/crab_proj/build-crab_body_kinematics-Desktop_Qt_5_6_0_GCC_64bit-Default/devel/lib/pkgconfig:/opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/home/af/ros_demo/devel_isolated/crab_joint_publisher/lib/pkgconfig:/home/af/ros_demo/devel_isolated/crab_body_kinematics/lib/pkgconfig:/home/af/ros_demo/devel_isolated/crab_msgs/lib/pkgconfig:/home/af/ros_demo/devel_isolated/crab_leg_kinematics/lib/pkgconfig:/home/af/ros_demo/devel_isolated/crab_gait/lib/pkgconfig:/home/af/ros_demo/devel_isolated/dynamxiel_action_client/lib/pkgconfig:/home/af/ros_demo/devel_isolated/dynamixel_tutorials/lib/pkgconfig:/home/af/ros_demo/devel_isolated/dynamixel_msgs/lib/pkgconfig:/home/af/ros_demo/devel_isolated/dynamixel_driver/lib/pkgconfig:/home/af/ros_demo/devel_isolated/dynamixel_controllers/lib/pkgconfig:/home/af/ros_demo/devel_isolated/rrbot_gazebo/lib/pkgconfig:/home/af/ros_demo/devel_isolated/rrbot_description/lib/pkgconfig:/home/af/ros_demo/devel_isolated/rrbot_control/lib/pkgconfig:/home/af/ros_demo/devel_isolated/pr2_controller_manager/lib/pkgconfig:/home/af/ros_demo/devel_isolated/pr2_mechanism_diagnostics/lib/pkgconfig:/home/af/ros_demo/devel_isolated/my_controller_pkg/lib/pkgconfig:/home/af/ros_demo/devel_isolated/pr2_controller_interface/lib/pkgconfig:/home/af/ros_demo/devel_isolated/pr2_mechanism_model/lib/pkgconfig:/home/af/ros_demo/devel_isolated/pr2_hardware_interface/lib/pkgconfig:/home/af/ros_demo/devel_isolated/pluginlib_calculator/lib/pkgconfig:/home/af/ros_demo/devel_isolated/my_pluginlib_calculator/lib/pkgconfig:/home/af/ros_demo/devel_isolated/gazebo_tutorials/lib/pkgconfig:/home/af/human_ws/devel/lib/pkgconfig:/home/af/moveit/devel/lib/pkgconfig:/home/af/hexapod_ws/devel/lib/pkgconfig:/home/af/catkin_ws/devel/lib/pkgconfig:/opt/ros/indigo/lib/pkgconfig"
export PWD="/home/af/hexapod_ws/src/crab_proj/build-crab_body_kinematics-Desktop_Qt_5_6_0_GCC_64bit-Default"
export ROSLISP_PACKAGE_DIRECTORIES="/home/af/hexapod_ws/src/crab_proj/build-crab_body_kinematics-Desktop_Qt_5_6_0_GCC_64bit-Default/devel/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/af/hexapod_ws/src/crab_proj/crab_body_kinematics:/home/af/ros_demo/src/crab_robot/crab_joint_publisher:/home/af/ros_demo/src/crab_robot/crab_body_kinematics:/home/af/ros_demo/src/crab_robot/crab_msgs:/home/af/ros_demo/src/crab_robot/crab_leg_kinematics:/home/af/ros_demo/src/crab_robot/crab_gait:/home/af/ros_demo/src/dynamixel_motor/dynamxiel_action_client:/home/af/ros_demo/src/dynamixel_motor/dynamixel_tutorials:/home/af/ros_demo/src/dynamixel_motor/dynamixel_msgs:/home/af/ros_demo/src/dynamixel_motor/dynamixel_motor:/home/af/ros_demo/src/dynamixel_motor/dynamixel_driver:/home/af/ros_demo/src/dynamixel_motor/dynamixel_controllers:/home/af/ros_demo/src/gazebo_ros_demos/rrbot_gazebo:/home/af/ros_demo/src/gazebo_ros_demos/rrbot_description:/home/af/ros_demo/src/gazebo_ros_demos/rrbot_control:/home/af/ros_demo/src/pr2_mechanism-indigo-devel/pr2_controller_manager:/home/af/ros_demo/src/pr2_mechanism-indigo-devel/pr2_mechanism_diagnostics:/home/af/ros_demo/src/my_controller_pkg:/home/af/ros_demo/src/pr2_mechanism-indigo-devel/pr2_controller_interface:/home/af/ros_demo/src/pr2_mechanism-indigo-devel/pr2_mechanism_model:/home/af/ros_demo/src/pr2_mechanism-indigo-devel/pr2_mechanism:/home/af/ros_demo/src/pr2_mechanism-indigo-devel/pr2_hardware_interface:/home/af/ros_demo/src/pluginlib_calculator:/home/af/ros_demo/src/my_pluginlib_calculator:/home/af/ros_demo/src/gazebo_ros_demos/custom_plugin_tutorial:/home/af/moveit/src:/home/af/hexapod_ws/src:/home/af/catkin_ws/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks"